export class FormularioConstantes {

	public static REGLAS_FORMUALRIO = [
		'cs_id_26', 
		'cs_id_32', 
		'cs_id_27', 
		'cs_id_33', 
		'cs_id_28', 
		'cs_id_34', 
		'cs_id_29', 
		'cs_id_35', 
		'cs_id_30', 
		'cs_id_36', 
		'cs_id_31', 
		'cs_id_37', 		
		{casilla: 'cs_id_38', redondear: true}, 
		{casilla: 'cs_id_39', redondear: true}, 
		{casilla: 'cs_id_40', redondear: true}, 
		{casilla: 'cs_id_41', redondear: true}, 
		{casilla: 'cs_id_42', redondear: true}, 
		{casilla: 'cs_id_43', redondear: true}, 
		//'cs_id_38', 
		//'cs_id_39', 
		//'cs_id_40', 
		//'cs_id_41', 
		//'cs_id_42', 
		//'cs_id_43', 
		'cs_id_44', 
		'cs_id_45', 
		'cs_id_46', 
		'cs_id_47', 
		'cs_id_48', 
		'cs_id_49', 
		'cs_id_50', 
		'cs_id_51', 
		'cs_id_52', 
		'cs_id_53', 
		'cs_id_54', 
		'cs_id_55', 
		'cs_id_56', 
		'cs_id_57', 
		'cs_id_58', 
		{casilla: 'cs_id_59', redondear: true}, 
		{casilla: 'cs_id_60', redondear: true},
		{casilla: 'cs_id_61', redondear: true},
		{casilla: 'cs_id_62', redondear: true},
		//'cs_id_59',
		//'cs_id_60', 
		//'cs_id_61', 
		//'cs_id_62', 	
		{casilla: 'cs_id_63', redondear: true},
		{casilla: 'cs_id_64', redondear: true},
		{casilla: 'cs_id_65', redondear: true},
		{casilla: 'cs_id_66', redondear: true},
		//'cs_id_63', 
		//'cs_id_64', 
		//'cs_id_65', 		
		//'cs_id_66'
	];

}
